### PR TITLE
Homie 2

### PR DESCRIPTION
**Pull request by sja**
I tried to fullfill the Homie 2 convention. I have no clue about Python, so any suggestion would be helpful.

### CODE REVIEW

**Comment by sja** [comment]
Ok, now I saw your dev branch. Damn.

The only solution my approach has better than yours: I determine the local mac address from the real  used network interface which is used to connect to the broker. Maybe that's something you find useful.

**Comment by jalmeroth** [comment]
@sja thanks for your contribution! I see you have invested quite some effort for this PR, but as the dev branch holds a lot of changes towards homie v2, I am honestly not so sure how to handle this situation best. In any case, I will need some time to review your changes, maybe I will cherry-pick some code, if that would be ok with you?

**Comment by sja** [comment]
Thats totally ok! I just made an approach which does not fullfill the complete convention. 
Feel free to close this PR. 

Freundliche Grüße 
Sebastian Janzen

**Comment by jalmeroth** [comment]
PR was integrated via bc602b12a2a49c18566e552a05b7c32232f0513b

**Pull request closed without merging**
